(in-package #:i18n-backend-icu)

(defmethod backend-make-plural-rules ((backend icu-backend) locale &key type)
  (declare (ignore backend))
  (with-foreign-object (err :int)
    (setf (mem-ref err :int) (%zero-error))
    (let* ((ptype (foreign-enum-value 'cl-stack-icu:u-plural-type
                                      (ecase (or type :cardinal)
                                        (:cardinal :cardinal)
                                        (:ordinal :ordinal))))
           (raw (cl-stack-icu:uplrules-open-for-type (%locale-tag locale) ptype err)))
      (cl-stack-icu:check-icu (mem-ref err :int) "uplrules-open")
      (make-instance 'plural-rules
                     :locale locale
                     :type (or type :cardinal)
                     :raw raw))))

(defmethod backend-plural-category ((backend icu-backend) rules number)
  (declare (ignore backend))
  (with-foreign-object (err :int)
    (setf (mem-ref err :int) (%zero-error))
    (let ((n (cl-stack-icu:uplrules-select (i18n-protocol::plural-rules-raw rules)
                                           (float number 1d0)
                                           (null-pointer) 0 err)))
      (setf (mem-ref err :int) (%zero-error))
      (with-foreign-pointer (buf (* (foreign-type-size 'cl-stack-icu:u-char)
                                    (1+ (max n 0))))
        (setf n (cl-stack-icu:uplrules-select (i18n-protocol::plural-rules-raw rules)
                                              (float number 1d0)
                                              buf (1+ n) err))
        (cl-stack-icu:check-icu (mem-ref err :int) "uplrules-select")
        (let ((s (cl-stack-icu:u-chars-to-lisp buf n)))
          (cond ((string= s "zero") :zero)
                ((string= s "one") :one)
                ((string= s "two") :two)
                ((string= s "few") :few)
                ((string= s "many") :many)
                (t :other)))))))
